module.exports = {
    error: '오류가 발생하였습니다.',
    errorRetry: '오류가 발생하였습니다. 잠시후 다시 시도해주세요.',
    saveMsg: '저장되었습니다.',
    updateMsg: '수정되었습니다.',
    deleteMsg: '삭제되었습니다.',
    requiredPartnerId: 'PartnerId is Required.',
    requiredPartnerName: 'PartnerName is Required.',
    requiredEntityId: 'EntityId is Required.',
    requiredOutletId: 'OutletId is Required.',
    requiredCategoryName: 'Category Name is Required.',
    requiredEntityName: 'Entity Name is Required.',
    requiredOutletName: 'Outlet Name is Required.',
    requiredSalesCounterName: 'Sales Counter Name is Required.',
    requiredName: 'Name is Required.',
    requiredEmail: 'Email is Required.',
    requiredPhoneNumber: 'Phone Number is Required.',
    requiredDesignation: 'Designation is Required.',
    requiredLogoImage: 'Logo Image is Required.',
    requiredDescription: 'Description Required.',
    failedWrongQrCode: '잘못된 QR 코드입니다.',
}